import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className=" h-screen flex justify-center items-center">
        <div className="max-w-md">{children}</div>
      </body>
    </html>
  );
}
